import os
import json
from typing import List, Dict, Any
from langchain_core.prompts import ChatPromptTemplate
from models import InterviewReport, FinalEvaluation, QuestionEvaluation, InterviewConfig
from chains.question_generator import get_llm

class ReportGeneratorChain:
    def __init__(self, prompt_path: str = "prompts/report_generation_prompt.txt"):
        with open(prompt_path, "r", encoding="utf-8") as f:
            template_text = f.read()
        self.prompt = ChatPromptTemplate.from_template(template_text)
        self.llm = get_llm()

    def generate_report(
        self,
        config: InterviewConfig,
        final_eval: FinalEvaluation,
        evaluations: List[QuestionEvaluation],
        topics_covered: List[str]
    ) -> InterviewReport:
        report = InterviewReport(
            domain=config.domain,
            difficulty=config.difficulty,
            experience_level=config.experience_level,
            total_questions_asked=len(evaluations),
            topics_covered=topics_covered,
            technical_score=final_eval.technical_score,
            communication_score=final_eval.communication_score,
            topic_performances=final_eval.topic_performances,
            strengths=final_eval.strengths,
            areas_for_improvement=final_eval.areas_for_improvement,
            improvement_suggestions=final_eval.improvement_suggestions,
            interview_outcome=final_eval.interview_outcome,
            recommendation_reason=final_eval.recommendation_reason,
            question_evaluations=evaluations
        )
        return report

    def render_markdown(self, report: InterviewReport) -> str:
        md = []
        md.append(f"# Technical Interview Performance Report")
        md.append(f"**Domain:** {report.domain} | **Initial Difficulty:** {report.difficulty} | **Experience Level:** {report.experience_level}")
        md.append(f"**Questions Asked:** {report.total_questions_asked} | **Topics Covered:** {', '.join(report.topics_covered)}")
        md.append("\n---\n")

        md.append("## Executive Performance Summary")
        md.append(f"- **Technical Score:** `{report.technical_score} / 100`")
        md.append(f"- **Communication Score:** `{report.communication_score} / 100`")
        md.append(f"- **Interview Outcome Recommendation:** `{report.interview_outcome}`")
        md.append(f"- **Evaluation Rationale:** {report.recommendation_reason}\n")

        md.append("## Topic-Level Performance Breakdown")
        md.append("| Topic | Questions Asked | Avg Question Score (0-10) | Mastery Percentage |")
        md.append("| :--- | :---: | :---: | :---: |")
        for tp in report.topic_performances:
            md.append(f"| {tp.topic} | {tp.questions_asked} | {tp.average_score} | {tp.percentage}% |")
        md.append("\n")

        md.append("## Demonstrated Strengths")
        for s in report.strengths:
            md.append(f"- {s}")
        md.append("\n")

        md.append("## Areas for Improvement")
        for a in report.areas_for_improvement:
            md.append(f"- {a}")
        md.append("\n")

        md.append("## Actionable Growth Suggestions")
        for i, sug in enumerate(report.improvement_suggestions, 1):
            md.append(f"{i}. {sug}")
        md.append("\n")

        md.append("## Question-by-Question Transcript & Evaluation")
        for i, qe in enumerate(report.question_evaluations, 1):
            md.append(f"### Question {i} [{qe.difficulty}] - {qe.topic}")
            md.append(f"**Prompt:** {qe.question}")
            md.append(f"**Candidate Response:** \"{qe.candidate_answer}\"")
            md.append(f"**Technical Score:** `{qe.technical_score}/10` | **Clarity Score:** `{qe.clarity_score}/10` | **Overall:** `{qe.overall_score}/10`")
            if qe.strengths:
                md.append(f"- **Strengths:** {', '.join(qe.strengths)}")
            if qe.missing_concepts:
                md.append(f"- **Missing Concepts:** {', '.join(qe.missing_concepts)}")
            md.append("")

        md.append("---\n*Disclaimer: This report was automatically generated by the AI Interview Simulator. Final hiring decisions should remain with human interviewers or recruiters.*")
        return "\n".join(md)

    def save_outputs(self, report: InterviewReport, output_dir: str = "outputs"):
        os.makedirs(output_dir, exist_ok=True)
        json_path = os.path.join(output_dir, "interview_report.json")
        md_path = os.path.join(output_dir, "interview_report.md")

        with open(json_path, "w", encoding="utf-8") as f:
            f.write(report.model_dump_json(indent=2))

        markdown_content = self.render_markdown(report)
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(markdown_content)
